using DSInternals.Win32.WebAuthn.Interop;

namespace DSInternals.Win32.WebAuthn.FIDO
{
    /// <summary>
    /// This enumeration contains attestation conveyance options for credential generation.
    /// </summary>
    /// <see>https://www.w3.org/TR/webauthn-2/#enum-attestation-convey</see>
    public enum AttestationConveyancePreference : int
    {
        /// <remarks>
        /// Corresponds to WEBAUTHN_ATTESTATION_CONVEYANCE_PREFERENCE_ANY.
        /// </remarks>
        Any = ApiConstants.AttestationConveyancePreferenceAny,

        /// <summary>
        /// This value indicates that the Relying Party is not interested in authenticator attestation.
        /// </summary>
        /// <remarks>
        /// Corresponds to WEBAUTHN_ATTESTATION_CONVEYANCE_PREFERENCE_NONE.
        /// </remarks>
        None = ApiConstants.AttestationConveyancePreferenceNone,

        /// <summary>
        /// This value indicates that the Relying Party prefers an attestation conveyance yielding verifiable attestation statements,
        /// but allows the client to decide how to obtain such attestation statements.
        /// </summary>
        /// <remarks>
        /// Corresponds to WEBAUTHN_ATTESTATION_CONVEYANCE_PREFERENCE_INDIRECT.
        /// </remarks>
        Indirect = ApiConstants.AttestationConveyancePreferenceIndirect,

        /// <summary>
        /// This value indicates that the Relying Party wants to receive the attestation statement as generated by the authenticator.
        /// </summary>
        /// <remarks>
        /// Corresponds to WEBAUTHN_ATTESTATION_CONVEYANCE_PREFERENCE_DIRECT.
        /// </remarks>
        Direct = ApiConstants.AttestationConveyancePreferenceDirect

        // TODO: Enterprise AttestationConveyancePreference
    }
}
