name: 'Build and Test'

on:
  push:
    paths:    
    - 'Src/**'
    - '.github/workflows/**'

jobs:
  build:
    name: 'Build'
    runs-on: windows-latest
    timeout-minutes: 10
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
          dotnet-version: |
            7.0.x
      env:
        DOTNET_INSTALL_DIR: 'C:\Program Files\dotnet'

    - name: Build
      working-directory: Src
      run: dotnet build --configuration Release

    - name: Create NuGet Packages
      working-directory: Src
      run: dotnet pack --configuration Release --no-build --nologo

    - name: Run Non-Interactive Unit Tests
      working-directory: Src
      run: dotnet test --filter TestCategory!=Interactive --configuration Debug --nologo
      continue-on-error: true
    
    - name: Install Coverage Report Generator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Generate Code Coverage Reports
      working-directory: Build/TestResults
      run: reportgenerator -reports:*/coverage.cobertura.xml -targetdir:. -reporttypes:"HtmlSummary" -title:"WebAuthn Interop Assembly"

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: TestResults
        path: |
            Build/TestResults/*.*
            !**/*.htm

    - name: Upload NuGet Packages
      uses: actions/upload-artifact@v3
      with:
        name: NuGet
        path: Build/bin/Release/Packages/*nupkg

    - name: Upload Desktop App
      uses: actions/upload-artifact@v3
      with:
        name: Fido2UI
        path: Build/bin/Release/Fido2UI/*
