name: CI

on:
  push:
    paths:    
    - 'Src/**'
    - '.github/workflows/**'

jobs:
  build:
    name: 'Release Build'
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Setup .NET Core CLI
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '3.1.x'

    - name: Build
      working-directory: Src
      run: dotnet build --configuration Release

    - name: Run Unit Tests
      working-directory: Src
      run: dotnet test DSInternals.Win32.WebAuthn.Tests --configuration Release
      continue-on-error: true
    
    - name: Install Coverage Report Generator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Generate Code Coverage Reports
      working-directory: Build/TestResults
      run: reportgenerator -reports:*/coverage.cobertura.xml -targetdir:. -reporttypes:"HtmlSummary;MHtml" -title:"WebAuthn Interop Assembly"

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: TestResults
        path: |
            Build/TestResults/*
            !**/*.htm

    - name: Upload NuGet Package
      uses: actions/upload-artifact@v2
      with:
        name: NuGet
        path: Build/bin/Release/DSInternals.Win32.WebAuthn/*nupkg

    - name: Upload Desktop App
      uses: actions/upload-artifact@v2
      with:
        name: Fido2UI
        path: Build/bin/Release/Fido2UI/net472/*
